version: '3'

silent: true

tasks:
  default:
    - task: build
  build: meson compile -C build
  run:
    - task: default
    - ./build/mamba
  test:
    - task: default
    - pytest
  format: clang-format -i *.mm *.h
  refresh-deps: meson subprojects update --reset
