[[language]]
name = "objective-cpp"
scope = "source.objc++"
roots = ["meson.build"]
language-id = "objective-cpp"
file-types = ["h", "mm"]
comment-token = "//"
indent = { tab-width = 4, unit = "    " }
language-servers = ["clangd"]
grammar = "cpp"
auto-format = true

[[language]]
name = "metal"
roots = []
scope = "source.metal"
injection-regex = "metal"
file-types = ["metal"]
comment-token = "//"
indent = { tab-width = 4, unit = "    " }
grammar = "cpp"
auto-format = true
